/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import org.jyothishaastra.Kaalas.Kaala;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.Calendar;
import java.util.TimeZone;
// import com.luckycatlabs.sunrisesunset.SunriseSunsetCalculator;

class NakshatraTest {

	@Test 
	void nakshatra() throws Exception {

	Calendar date = Calendar.getInstance();
	date.setTimeZone(TimeZone.getTimeZone("UT"));
	date.set(2009, 6, 15, 0, 0, 0); // for 15 July 2009

	// set to IST
	long gmtTime = date.getTime().getTime();
	long timezoneAlteredTime = gmtTime + TimeZone.getTimeZone("Asia/Calcutta").getRawOffset();
	date = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
	date.setTimeInMillis(timezoneAlteredTime);

	double ayanamsha = Ayanaamsha.ayanamsha(date);

	// 23.9853731 in pdf
	assertEquals(23.992896251386888, ayanamsha);
	assertArrayEquals(new int[]{ 23, 59, 34 }, DegMinSec.getGeoCoordsFromDegree(ayanamsha));

	int swissEphermesisMoon[] = { 17, 41, 00 };
	int swissEphermesisSun[] = { 22, 39, 28 };
	int surRaashi = 4; // Karkaataka
	int chaRaashi = 1; // Mesha

	int chaRaashi1 = 2; // on 16 July 2009 it is in Vrushabha
	int chandraAbs1[] = new int[]{ 00, 50, 00 };
	chandraAbs1[0] = DegMinSec.absGeo(chaRaashi1, chandraAbs1);
	assertArrayEquals(new int[]{30, 50, 0}, chandraAbs1);

	int chandraAbs[] = Arrays.copyOf(swissEphermesisMoon, swissEphermesisMoon.length);
	chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);
	// Do not use swissEphermesisMoon anymore

	assertArrayEquals(new int[]{17, 41, 0}, chandraAbs);

	int sooryaAbs[] = Arrays.copyOf(swissEphermesisSun, swissEphermesisSun.length);
	sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);
	// Do not use swissEphermesisSun anymore

	assertArrayEquals(new int[]{112, 39, 28}, sooryaAbs);
	// assertArrayEquals(new int[]{22, 39, 28}, swissEphermesisSun);

	double ayaNir = Ayanaamsha.nirayaana(ayanamsha, chandraAbs);
	// System.out.printf("ayaNir %s\n", ayaNir); 
	int[] chaNir = DegMinSec.getGeoCoordsFromDegree(ayaNir);
	// System.out.printf("chaNir %s\n", Arrays.toString(chaNir)); 
	String naks = Nakshatra.nakshatra(chaNir);
	assertEquals("Revathi - 7.023888889 deg have elapsed", naks);
	assertEquals(26, Nakshatra.nakshatraIndex);
	// assertArrayEquals(new int[]{7,1,26}, Nakshatra.getElapsed(), "Elapsed is not " + Arrays.toString(Nakshatra.getElapsed())); // 13, 9, 0

	// System.out.printf("res %s\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Nakshatra.remainingDistance))); 
	assertArrayEquals(new int[]{6,18,34}, DegMinSec.getGeoCoordsFromDegree(Nakshatra.remainingDistance)); // , 34

	assertEquals(6.309444444444466, Nakshatra.remainingDistance);
	assertArrayEquals(new int[]{6,18,34}, DegMinSec.getGeoCoordsFromDegree(Nakshatra.remainingDistance)); // ,8}

	// daily motion of Chandra
	int chaMot[] = DegMinSec.minus(chandraAbs, chandraAbs1);
	// System.out.printf("chaMot %s", Arrays.toString(chaMot)); // 265, 1, 32

	assertArrayEquals(new int[]{13,9,0}, chaMot); // 13, 9, 0
	
	// chaMot = new int[]{13, 9, 0};
	// assertEquals(0.5713662833353618, Nakshatra.end(chaMot, Nakshatra.remainingDistance));
	assertArrayEquals(new int[]{11, 30, 55}, DegMinSec.getGeoCoordsFromDegree(Nakshatra.end(chaMot, Nakshatra.remainingDistance))); // , 8}

	Calendar naksStart = Nakshatra.start(date);
	System.out.printf("Nakshatra start is %s in IST.\n", naksStart.toInstant());
	// assertEquals(1247590714l, naksStart.getTimeInMillis()/1000, "Nakshatra start is " + naksStart.getTimeInMillis());
	assertEquals(1247610514l, naksStart.getTimeInMillis()/1000, "Nakshatra start is " + naksStart.getTimeInMillis());
	Calendar naksEnd = Nakshatra.getNakshatraEnd(date);
	
	assertEquals(1247677255l, naksEnd.getTimeInMillis()/1000);
	System.out.printf("Nakshatra end is %s in IST\n", naksEnd.toInstant());

	Calendar amrSta = Nakshatra.amruVarjStart(true);
	assertEquals(1247673694l, amrSta.getTimeInMillis()/1000);
	System.out.printf("Amrutha start is %s in IST.\n", amrSta.toInstant());

	Calendar amrEnd = Nakshatra.amruVarjEnd(true);
	assertEquals(1247678674l, amrEnd.getTimeInMillis()/1000);
	System.out.printf("Amrutha end is %s in IST.\n", amrEnd.toInstant());
	
	Calendar varjSta = Nakshatra.amruVarjStart(false);
	assertEquals(1247681374l, varjSta.getTimeInMillis()/1000);
	System.out.printf("Varjya start is %s in IST.\n", varjSta.toInstant());

	Calendar varjEnd = Nakshatra.amruVarjEnd(false);
	assertEquals(1247686354l, varjEnd.getTimeInMillis()/1000);
	System.out.printf("Varjya end is %s in IST.\n", varjEnd.toInstant());

    double latitude = 49.202347531821296;
    double longitude = -122.91647403420454;
	/* 
	Calendar[] sunriseSunset = ca.rmen.sunrisesunset.SunriseSunset.getSunriseSunset(Calendar.getInstance(), latitude, longitude);
	System.out.println("Sunrise at: " + sunriseSunset[0].getTime());
	System.out.println("Sunset at: " + sunriseSunset[1].getTime());
	*/

	Calendar date1 = Calendar.getInstance();
	// date1.set(Calendar.DATE, 26);
	date1.set(2009, 6, 15, 0, 0, 0); // for 15 July 2009

	// try setting hours to 00 to avoid issues
	date1.set(Calendar.HOUR_OF_DAY, 0);

	System.out.println("Caclculating for date " + date1.getTime());
	Sunrise.calc(date1, latitude, longitude, "");
	int srHour = Sunrise.sunrise.get(Calendar.HOUR_OF_DAY);
	int srMin = Sunrise.sunrise.get(Calendar.MINUTE);

	int ssHour = Sunrise.sunset.get(Calendar.HOUR_OF_DAY);
	int ssMin = Sunrise.sunset.get(Calendar.MINUTE);

	int weekday = Sunrise.sunrise.get(Calendar.DAY_OF_WEEK) - 1; // as using Sunday to be 0
	System.out.printf("Day of week is %d\n", weekday);
	int[] raahu = Kaalas.kaala(new int[]{srHour, srMin, 0}, new int[]{ ssHour, ssMin, 0 }, weekday, Kaala.Raahu);
	System.out.printf("Raahu kaala starts at %s\n", Arrays.toString(raahu));
	int[] guli = Kaalas.kaala(new int[]{srHour, srMin, 0}, new int[]{ ssHour, ssMin, 0 }, weekday, Kaala.Guli);
	System.out.printf("Guli kaala starts at %s\n", Arrays.toString(guli));
	int[] yama = Kaalas.kaala(new int[]{srHour, srMin, 0}, new int[]{ ssHour, ssMin, 0 }, weekday, Kaala.Yama);
	System.out.printf("Yama kaala starts at %s\n", Arrays.toString(yama));
	System.out.printf("Duration of any kaala is %s hours\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Kaalas.duration)));

	Kaalas.durmuhurtha(new int[]{srHour, srMin, 0}, weekday);
	}
}

