/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.jyothishaastra.Kaalas.Kaala;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.stream.Stream;

class NakshatraMonthTest {

	private static Stream<Arguments> sidEph() {
		Calendar date = Calendar.getInstance(TimeZone.getTimeZone("UT"));
		date.set(2025, 11, 1, 0, 0, 0); // for December 2025

		// Soorya
		return Stream.of(
				//( day, sayyana from Swiss, niraaya from Ind, raashi from Swiss )
				Arguments.of(1, date, new int[]{ 19, 14, 0 }, new int[]{ 3, 48, 0 }, 11, 0 ),
				Arguments.of(2, date, new int[]{ 3, 48, 0 }, new int[]{ 18, 45, 0 }, 0, 0 ),
				Arguments.of(3, date, new int[]{ 18, 45, 0 }, new int[]{ 3, 59, 0 }, 0, 1 )
				);
	}

	@ParameterizedTest
	@MethodSource("sidEph")
	void calcNaks(int day, Calendar date, int []ephCha, int[] ephCha1, int raaCha, int raaCha1) throws Exception {

		date.set(Calendar.DATE, day);

		System.out.println("-----------------------------------------------");
		System.out.printf("Calculations for %s GMT\n", date.toInstant());

		// need this when Naks moves from say 353 deg Meena to 3 deg Mesha
		int subs = raaCha1;
		if(raaCha1 < raaCha)
			subs = raaCha + 1;

		ephCha1[0] = DegMinSec.absGeo(subs, ephCha1);
		// ephSoor1[0] = DegMinSec.absGeo(raaSoo1, ephSoor1);

		int ephChaAbs[] = Arrays.copyOf(ephCha, ephCha.length);
		ephChaAbs[0] = DegMinSec.absGeo(raaCha, ephCha);
		System.out.printf("Chandra abs %s\n", Arrays.toString(ephChaAbs));

		// int ephSoorAbs[] = Arrays.copyOf(ephSoor, ephSoor.length);
		// ephSoorAbs[0] = DegMinSec.absGeo(raaSoo, ephSoor);
		// System.out.printf("Soorya abs %s\n", Arrays.toString(sooryaAbs));

		// daily motion of Chandra
		int chaMot[] = DegMinSec.minusMoreThreeSixty(ephChaAbs, ephCha1);
		// int surMot[] = DegMinSec.minus(ephSoorAbs, ephSoor1);
		System.out.printf("chaMot %s\n", Arrays.toString(chaMot)); // 345, 26, 0
		// chaMot = new int[]{14, 34, 0};

		String raashi = Raashi.raashi(ephChaAbs); 
		// System.out.printf("Raashi is %s and remaining distance is %4.9f for Chandra Niraayana %s.\n", raashi, Raashi.remainingDistance, Arrays.toString(ephChaAbs));
		System.out.printf("Raashi is %s.\n", raashi);

		String naks = Nakshatra.nakshatra(ephChaAbs);
		System.out.printf("Nakshatra is %s\n", naks); 
		System.out.printf("Nakshatra RD is %8.6f\n", Nakshatra.remainingDistance); 

		Nakshatra.end(chaMot, Nakshatra.remainingDistance);

		double naksStart = Nakshatra.start(chaMot, Nakshatra.elapsed);
		System.out.printf("Nakshatra started %s GMT ago.\n", Arrays.toString(Nakshatra.staArr));
		System.out.printf("Nakshatra ends at %s GMT.\n", Arrays.toString(Nakshatra.endArr));
		// time is needed only from here
		Calendar naksStart_ = Nakshatra.absStart(date);
		System.out.printf("Nakshatra start is %s in GMT.\n", naksStart_.toInstant());
		Calendar naksEnd = Nakshatra.absEnd(date);
		System.out.printf("Nakshatra end is %s in GMT\n", naksEnd.toInstant());

		// use TimeZone.getAvailaibleIDs on your machine to confirm if the TZ is available
		// var tzId = "US/Pacific";
		var tzId = "GMT";
		if(TimeZone.getTimeZone(tzId).getID() != tzId){
			System.out.printf("Cannot continue as %s TZ is not available.\n", tzId);
			return;
		}

		Calendar amrSta = Nakshatra.amruVarjStart(true);
		var start = amrSta.toInstant().atZone(TimeZone.getTimeZone(tzId).toZoneId());

		System.out.printf("Amrutha start is %s.\n", start.toString());

		Calendar amrEnd = Nakshatra.amruVarjEnd(true);
		var end = amrEnd.toInstant().atZone(TimeZone.getTimeZone(tzId).toZoneId());
		System.out.printf("Amrutha end is %s.\n", end.toString());

		Calendar varjSta = Nakshatra.amruVarjStart(false);
		start = varjSta.toInstant().atZone(TimeZone.getTimeZone(tzId).toZoneId());
		System.out.printf("Varjya start is %s.\n", start.toString());

		Calendar varjEnd = Nakshatra.amruVarjEnd(false);
		end = varjEnd.toInstant().atZone(TimeZone.getTimeZone(tzId).toZoneId());
		System.out.printf("Varjya end is %s.\n", end.toString());
		System.out.println("-----------------------------------------------");
	}
}
