/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Calendar;

class TithiTest {
	@Test void raashi() throws Exception {

	Calendar date = Calendar.getInstance();
	date.set(2009, 6, 15); // for 15 July 2009

	double ayanamsha = Ayanaamsha.ayanamsha(date);

	// 23.9853731 in pdf
	assertEquals(23.992896251386888, ayanamsha);
	assertArrayEquals(new int[]{ 23, 59, 34 }, DegMinSec.getGeoCoordsFromDegree(ayanamsha));

	int swissEphermesisMoon[] = { 17, 41, 00 };
	int swissEphermesisSun[] = { 22, 39, 28 };
	int surRaashi = 4; // Karkaataka
	int chaRaashi = 1; // Mesha

	int chandraAbs[] = swissEphermesisMoon;
	chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);

	int sooryaAbs[] = swissEphermesisSun;
	sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);

	// assertEquals("Padya - 5.271666667 deg have elapsed", Tithi.tithi(chandraAbs, sooryaAbs));
	assertEquals("Krishna Bahula - Ashtami - 1.025555556 deg have elapsed", Tithi.tithi(chandraAbs, sooryaAbs));
	// assertEquals(6.728333333, Tithi.remainingDistance);
	assertEquals(10.974444444444487, Tithi.remainingDistance);

	// Tithi is  - Padya - 5.271666667 deg have elapsed and remaining distance is 6.728333333.
	// Tithi ends at [0, 38, 37] from 5:30 IST following day or from 5pm in PST? which is from midnight UT.
	}
}
