/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.Calendar;

class TithiTest {
	@Test void raashi() throws Exception {

	Calendar date = Calendar.getInstance();
	date.set(2009, 6, 15); // for 15 July 2009

	double ayanamsha = Ayanaamsha.ayanamsha(date);

	// 23.9853731 in pdf
	assertEquals(23.992896251386888, ayanamsha);
	assertArrayEquals(new int[]{ 23, 59, 34 }, DegMinSec.getGeoCoordsFromDegree(ayanamsha));

	int swissEphermesisMoon[] = { 17, 41, 00 };
	int swissEphermesisSun[] = { 22, 39, 28 };
	int surRaashi = 3; // Karkaataka
	int chaRaashi = 0; // Mesha

	int chaRaashi1 = 1; // on 16 July 2009 it is in Vrushabha
	int chandraAbs1[] = new int[]{ 00, 50, 00 };
	chandraAbs1[0] = DegMinSec.absGeo(chaRaashi1, chandraAbs1);
	assertArrayEquals(new int[]{30, 50, 0}, chandraAbs1);

	int sooryaRaashi1 = 3; // on 16 July 2009 it is in Karkaataka itself
	int sooryaAbs1[] = new int[]{ 23, 36, 42 };
	sooryaAbs1[0] = DegMinSec.absGeo(sooryaRaashi1, sooryaAbs1);
	assertArrayEquals(new int[]{113, 36, 42}, sooryaAbs1);

	int chandraAbs[] = Arrays.copyOf(swissEphermesisMoon, swissEphermesisMoon.length);
	chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);
	assertArrayEquals(new int[]{17, 41, 0}, chandraAbs);

	int sooryaAbs[] = Arrays.copyOf(swissEphermesisSun, swissEphermesisSun.length);
	sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);
	assertArrayEquals(new int[]{112, 39, 28}, sooryaAbs);

	// assertEquals("Padya - 5.271666667 deg have elapsed", Tithi.tithi(chandraAbs, sooryaAbs));
	assertEquals("Krishna Bahula - Ashtami - 1.025555556 deg have elapsed", Tithi.tithi(chandraAbs, sooryaAbs));
	// assertEquals(6.728333333, Tithi.remainingDistance);
	// assertEquals(1.025555555555556, Tithi.remainingDistance);
	assertEquals(10.974444444444487, Tithi.remainingDistance);

	// daily motion of Chandra
	int chaMot[] = DegMinSec.minus(chandraAbs, chandraAbs1);
	assertArrayEquals(new int[]{13, 9, 0}, chaMot);
	assertArrayEquals(new int[]{113, 36, 42}, sooryaAbs1);
	assertArrayEquals(new int[]{112, 39, 28}, sooryaAbs);
	int surMot[] = DegMinSec.minus(sooryaAbs, sooryaAbs1);
	// assertArrayEquals(new int[]{1, 3, 14}, surMot);
	assertArrayEquals(new int[]{0, 57, 14}, surMot, "Surmot is " + Arrays.toString(surMot));

	// assertEquals(10.974444444444487, Tithi.end(surMot,chaMot, Tithi.remainingDistance));
	// assertEquals(21.595954, Tithi.end(surMot,chaMot, Tithi.remainingDistance));
	var tithiEnd = Tithi.end(surMot,chaMot, Tithi.remainingDistance);
	assertEquals(21.59595499476162, tithiEnd);
	var tithiEndArr = DegMinSec.getGeoCoordsFromDegree(tithiEnd);
	assertArrayEquals(new int[]{21, 35, 45}, tithiEndArr, "tithi End is not " + Arrays.toString(tithiEndArr));
	// Tithi is  - Padya - 5.271666667 deg have elapsed and remaining distance is 6.728333333.
	// Tithi ends at [0, 38, 37] from 5:30 IST following day or from 5pm in PST? which is from midnight UT.
	}
}
