/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.Calendar;
class YogaTest {

	@Test 
	void yoga() throws Exception {

	Calendar date = Calendar.getInstance();
	date.set(2009, 6, 15); // for 15 July 2009

	double ayanamsha = Ayanaamsha.ayanamsha(date);

	// 23.9853731 in pdf
	assertEquals(23.992896251386888, ayanamsha);
	assertArrayEquals(new int[]{ 23, 59, 34 }, DegMinSec.getGeoCoordsFromDegree(ayanamsha));

	int swissEphermesisMoon[] = { 17, 41, 00 };
	int swissEphermesisSun[] = { 22, 39, 28 };
	int surRaashi = 4; // Karkaataka
	int chaRaashi = 1; // Mesha

	int chaRaashi1 = 2; // on 16 July 2009 it is in Vrushabha
	int chandraAbs1[] = new int[]{ 00, 50, 00 };
	chandraAbs1[0] = DegMinSec.absGeo(chaRaashi1, chandraAbs1);
	assertArrayEquals(new int[]{30, 50, 0}, chandraAbs1);

	int chandraAbs[] = Arrays.copyOf(swissEphermesisMoon, swissEphermesisMoon.length);
	chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);
	// Do not use swissEphermesisMoon anymore

	assertArrayEquals(new int[]{17, 41, 0}, chandraAbs);

	int sooryaAbs[] = Arrays.copyOf(swissEphermesisSun, swissEphermesisSun.length);
	sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);
	// Do not use swissEphermesisSun anymore

	assertArrayEquals(new int[]{112, 39, 28}, sooryaAbs);
	// assertArrayEquals(new int[]{22, 39, 28}, swissEphermesisSun);

	int surRaashi1 = 4; // on 16 July 2009 it is in 
	int sooryaAbs1[] = new int[]{ 23, 36, 42 };
	sooryaAbs1[0] = DegMinSec.absGeo(surRaashi1, sooryaAbs1);
	assertArrayEquals(new int[]{113, 36, 42}, sooryaAbs1, "Soory abs is " + Arrays.toString(sooryaAbs1));

	double ayaNir = Ayanaamsha.nirayaana(ayanamsha, chandraAbs);
	// System.out.printf("ayaNir %s\n", ayaNir); 
	int[] chaNir = DegMinSec.getGeoCoordsFromDegree(ayaNir);
	assertArrayEquals(new int[]{353, 41, 26}, chaNir, "chaNir is " + Arrays.toString(chaNir)); // ,8}

	int soorNir[] = DegMinSec.getGeoCoordsFromDegree(Ayanaamsha.nirayaana(ayanamsha, sooryaAbs));
	assertArrayEquals(new int[]{88, 39, 54}, soorNir, "soorNir is " + Arrays.toString(soorNir)); // ,8}

	String yoga = Yoga.yoga(chaNir, soorNir);
	assertEquals("Sukarma - 2.355555556 deg have elapsed", yoga);

	assertEquals(10.977777777777789, Yoga.remainingDistance); // , 34
	int [] res = DegMinSec.getGeoCoordsFromDegree(Yoga.remainingDistance);
	assertArrayEquals(new int[]{10,58,40}, res, "RD is " + Arrays.toString(res)); // ,8}

	// daily motion of Chandra
	int chaMot[] = DegMinSec.minus(chandraAbs, chandraAbs1);
	int surMot[] = DegMinSec.minus(sooryaAbs, sooryaAbs1);
	// System.out.printf("chaMot %s", Arrays.toString(chaMot)); // 265, 1, 32

	assertArrayEquals(new int[]{13,9,0}, chaMot); // 13, 9, 0
	assertArrayEquals(new int[]{0,57,14}, surMot, "SurMot is " + Arrays.toString(surMot)); // 13, 9, 0
	
	// chaMot = new int[]{13, 9, 0};
	res = DegMinSec.getGeoCoordsFromDegree(Yoga.end(chaMot, surMot));
	assertArrayEquals(new int[]{18, 40, 50}, res, "End is " + Arrays.toString(res)); // , 8}
	}
}
