/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import java.time.ZoneId;
import java.util.Arrays;
import java.util.Calendar;
import java.util.TimeZone;

public class App {
    public String getGreeting() {
        return "Hello Welcome to Jyoothi shaasthra!";
    }

	/* 
	   javac jyotishaastra/Ayanamsha.java
	   java jyotishaastra/DegMinSec.java
	   */
	public static void main(String ags[]) throws Exception {

		// Mesha is 1
		//  for 22nd Oct
		int chaRaashi = 8;
		int swissEphermesisMoon[] = { 4, 7, 00 };
		int swissEphCha1[] = Arrays.copyOf(swissEphermesisMoon, swissEphermesisMoon.length); // of next day's which is in Mesha raashi 9
		int swissEphCha2[] = { 16, 1, 0 }; // of next day's which is in Mesha raashi 9

		int surRaashi = 7;
		int swissEphermesisSun[] = { 28, 50, 42 };
		int swissEphSur1[] = Arrays.copyOf(swissEphermesisSun, swissEphermesisSun.length);
		int swissEphSur2[] = { 29, 50, 25 };

		// India Ephemersis doesnt have Ayanamsha
		Calendar date = Calendar.getInstance();
		date.setTimeZone(TimeZone.getTimeZone("UT"));
		date.set(2025, 9, 22, 0, 0, 0); 
        System.out.println(new App().getGreeting() + " at " + date.toInstant());

		/*

		// for 15 July 2009
		int surRaashi = 4; // Karkaataka
		int chaRaashi = 1; // Mesha
		int swissEphermesisMoon[] = { 17, 41, 00 };
		int ar1[] = { 17, 41, 00 }; // of next day's which is in Mesha raashi 9
		int ar2[] = { 0, 50, 0 }; // of next day's which is Vrushabha
		int swissEphermesisSun[] = { 22, 39, 28 };
		int ar3[] = { 22, 39, 28 };
		int ar4[] = { 23, 36, 42 };

		// India Ephemersis doesnt have Ayanamsha
		Calendar date = Calendar.getInstance();
		date.set(2009, 6, 15); // for 15 July 2009
							   // date.set(2009, 7, 15); // for 15 July 2009
							   */
		/* 
		   From Indian Astronomical ephemeris we straightaway get the Nirayana
		   longitudes for Ravi and Chandra at 5:29 AM IST on 15-7-2009. The values
are:
Ravi = 88-39’-45’
Chandra = 353-40’-26”

112-39’-28”
- 23-59’-34”
------------
88-39’-54” which is same as that we obtained from Indian
astronomical ephemeris.

Chandra’s longitude is 17-41’ in Aries. Subtracting Ayanamsa we get
353-41’-26” very near to that we obtain from Indian ephemeris.
*/

		double ayanamsha = Ayanaamsha.ayanamsha(date);
		System.out.printf("Aya is %s degrees for %s\n", ayanamsha, date.toInstant());	
		// System.out.printf("Aya is %s degrees\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(ayanamsha)));	
		// ayanamsha = 23.9928962;

		int chandraAbs[] = swissEphermesisMoon;
		chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);

		int sooryaAbs[] = swissEphermesisSun;
		sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);
		System.out.printf("Abs geo of Surya is %d & Chandra is %d\n", sooryaAbs[0], chandraAbs[0]);

		System.out.printf("Tithi is %s and remaining distance is %4.9f.\n", Tithi.tithi(chandraAbs, sooryaAbs), Tithi.remainingDistance);

		/*uncomment when Chandra has moved to next Raashi 
		*/
		// ar1[0] = DegMinSec.absGeo(chaRaashi, ar1);
		// chaRaashi = chaRaashi + 1; // since it is moving to next raashi
		swissEphCha2[0] = DegMinSec.absGeo(chaRaashi, swissEphCha2);

		int surMot[] = DegMinSec.minus(swissEphSur1, swissEphSur2);
		System.out.printf("Daily motion of Soorya is %s\n", Arrays.toString(surMot));

		int chaMot[] = DegMinSec.minus(swissEphCha1, swissEphCha2);
		System.out.printf("Daily motion of Chandra is %s\n", Arrays.toString(chaMot));

		// Time taken to cover remainingDistance
		String suff = "from 5:30 IST following day or from 5pm in PST? which is from midnight UT.";
		System.out.printf("Tithi ends at %s %s\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Tithi.end(surMot, chaMot, Tithi.remainingDistance))), suff);

		System.out.printf("Karana is %s and remaining distance is %4.9f.\n", Karana.karana(chandraAbs, sooryaAbs), Karana.remainingDistance);
		// System.out.printf("Karana ends at %s from 5:30 IST or minus from 5pm in PST?\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Karana.tithiEnd(surMot, chaMot, Tithi.remainingDistance))));

		int surNir[] = DegMinSec.getGeoCoordsFromDegree(Ayanaamsha.nirayaana(ayanamsha, sooryaAbs));
		// System.out.printf("Soorya niraayana on %s from Swiss is %s\n", date.getTime(), Arrays.toString(surNir));	

		int[] chaNir = DegMinSec.getGeoCoordsFromDegree(Ayanaamsha.nirayaana(ayanamsha, chandraAbs));
		System.out.printf("Chandra niraayana on %s from Swiss is %s\n", date.getTime(), Arrays.toString(chaNir));	

		// static from pdf, this is not from Indian Eph, not from Swiss Eph calc, but something newer, lol
		// chaNir = new int[]{ 353, 41, 52 };

		System.out.printf("Raashi is %s and remaining distance is %4.9f for Chandra Niraayana %s.\n", Raashi.raashi(chaNir), Raashi.remainingDistance, Arrays.toString(chaNir));

		// System.out.printf("Raashi ends at %s from 5:30 IST or minus from 5pm in PST?\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Raashi.tithiEnd(surMot, chaMot, Tithi.remainingDistance))));
		System.out.printf("Nakshatra is %s and remaining distance is %4.9f.\n", Nakshatra.nakshatra(chaNir), Nakshatra.remainingDistance);

		System.out.printf("Nakshatra start is %s in UT.\n", Nakshatra.start(date).toInstant());

		// "Nakshatra ends at %s from 5:30 IST or minus from 5pm in PST?\n"
		var naksEnd = Nakshatra.end(chaMot, Nakshatra.remainingDistance);
		System.out.printf("Nakshatra ends at %s %s %s\n", naksEnd, Arrays.toString(DegMinSec.getGeoCoordsFromDegree(naksEnd)), suff);
		// System.out.printf("Nakshatra ends at %s for Cha mot %s and RD %s\n", Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Nakshatra.end(chaMot, Nakshatra.remainingDistance))), Arrays.toString(chaMot), Arrays.toString(DegMinSec.getGeoCoordsFromDegree(Nakshatra.remainingDistance)));

		String yoga = Yoga.yoga(chaNir, surNir);
		System.out.printf("Yoga is %s and remaining distance is %4.9f.\n", yoga, Yoga.remainingDistance);

		var yogaEnd = Yoga.end(chaMot, surMot);
		System.out.printf("Yoga ends at %s %s %s\n", yogaEnd, Arrays.toString(DegMinSec.getGeoCoordsFromDegree(yogaEnd)), suff);
	}

}
